### ISSUE TITLE
Remove the folder `.gitignore`

### ISSUE THREAD

**Issue by cjpatoilo** [ArunMichaelDsouza/CSS-Mint#3]
Hello @ArunMichaelDsouza 

To remove the folder `.gitignore` you must first delete and then register this action in git. So she will not be in the repository. 
#2

**Comment by cjpatoilo** [comment]
#2

**Comment by ArunMichaelDsouza** [comment]
Fixed in [246efb2](https://github.com/ArunMichaelDsouza/CSS-Mint/commit/246efb2bd20ca6483081e82ba7a40fe775136b98).
